#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2014 uralbash <root@uralbash.ru>
#
# Distributed under terms of the MIT license.
sudo: false
language: python

notifications:
  email: "sacrud@uralbash.ru"
  email: "arkadiy@bk.ru"
  irc: "chat.freenode.net#sacrud"

python:
  - "2.7"
  - "3.3"
  - "3.4"

script:
  - python setup.py nosetests

after_success:
  - pip install coveralls
  - coveralls
